/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';



const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./src",
    files: "**/*.stories.?(ts|tsx)",
    importPathMatcher: /^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(?:ts|tsx)?)$/,
    // @ts-ignore
    req: require.context(
      '../src',
      true,
      /^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(?:ts|tsx)?)$/
    ),
  },
  {
    titlePrefix: "",
    directory: "./src/stories",
    files: "**/*.stories.?(ts|tsx)",
    importPathMatcher: /^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(?:ts|tsx)?)$/,
    // @ts-ignore
    req: require.context(
      '../src/stories',
      true,
      /^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(?:ts|tsx)?)$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var STORYBOOK_WEBSOCKET: { host: string; port: number } | undefined;
}


const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview")
];

globalThis.STORIES = normalizedStories;


// @ts-ignore
module?.hot?.accept?.();



if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,

  });
} else {
  updateView(globalThis.view, annotations, normalizedStories);
}

export const view: View = globalThis.view;
